name: CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install --no-root
    - name: Run tests
      run: poetry run python run_tests.py
